### ISSUE TITLE
Contributing to corefx?

### ISSUE THREAD

**Issue by xied75** [QRCS-CORP/CEX-NET#1]
Hi, John (Or others in the team)

I was led here by the codeproject article. It is great you have a base here on GitHub. It's much easier for collaboration. (one suggestion: maybe you can create an organization for your company and move your repos under the company name).

I assume you know that .NET is open sourced including the CoreCLR and CoreFX, I have raised some issues that are exactly in your expertise:

https://github.com/dotnet/corefx/issues/4581
https://github.com/dotnet/corefx/issues/4610

I believe there are much more open issues that you guys can contribute. So, selling libraries/support aside, instead of making a 3rd party library, why not get your great work into the Core? It will have much impact long term.

Best regards,

Dong

**Comment by QRCS-CORP** [comment]
Hi Dong,
I'd like to contribute, maybe at some future date, (too many projects, too little time). Thanks for asking though..

John
