### ISSUE TITLE
NuGet?

### ISSUE THREAD

**Issue by picrap** [QRCS-CORP/CEX-NET#2]
Hi,

Though I haven't tested your library right now (I'm planning to do it today anyway), I thought it could be interesting to make NuGet packages.
There is a way to automate all this (building and publishing), so once it is setup, every commit with a new version can push a new package.
If you're interested, I can help, all you will have to do is to register accounts on appveyor and NuGet, and provide some API keys, I'll do the rest ;)

Let me know!

**Comment by QRCS-CORP** [comment]
Hi Pascal,
I won't be adding this to NuGet at this time, but I appreciate the offer to help. 
The symmetric portion of this library is due for a big update, probably around the end of March, when I will begin mirroring improvements from the C++ version, I'll review the decision then.

Thanks, though..
